// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sellcar.data.Concrete.EfCore;

namespace sellcar.data.Migrations
{
    [DbContext(typeof(SellCarContext))]
    [Migration("20201007201758_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("sellcar.entity.Fav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.ToTable("Favs");
                });

            modelBuilder.Entity("sellcar.entity.Il", b =>
                {
                    b.Property<int>("ilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adi")
                        .HasColumnType("TEXT");

                    b.HasKey("ilId");

                    b.ToTable("Iller");
                });

            modelBuilder.Entity("sellcar.entity.Ilan", b =>
                {
                    b.Property<int>("IlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("azamiSurati")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cekisTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("durum")
                        .HasColumnType("TEXT");

                    b.Property<double>("fiyat")
                        .HasColumnType("REAL");

                    b.Property<double>("hizlanma")
                        .HasColumnType("REAL");

                    b.Property<int>("ilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ilanBasligi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ilanDetay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ilanTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("kapiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kasaTipi")
                        .HasColumnType("TEXT");

                    b.Property<int>("kilometre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("kimden")
                        .HasColumnType("TEXT");

                    b.Property<int>("markaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("model")
                        .HasColumnType("TEXT");

                    b.Property<int>("motorGücü")
                        .HasColumnType("INTEGER");

                    b.Property<int>("motorHacmi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ortalamaTuketim")
                        .HasColumnType("REAL");

                    b.Property<string>("renk")
                        .HasColumnType("TEXT");

                    b.Property<double>("sehirDisiTuketim")
                        .HasColumnType("REAL");

                    b.Property<double>("sehirIciTuketim")
                        .HasColumnType("REAL");

                    b.Property<string>("seri")
                        .HasColumnType("TEXT");

                    b.Property<string>("takas")
                        .HasColumnType("TEXT");

                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.Property<int>("vitesSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vitesTipi")
                        .HasColumnType("TEXT");

                    b.Property<int>("yakitDepoHacmi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("yakitTipi")
                        .HasColumnType("TEXT");

                    b.Property<int>("yil")
                        .HasColumnType("INTEGER");

                    b.HasKey("IlanId");

                    b.HasIndex("ilId");

                    b.HasIndex("markaId");

                    b.ToTable("Ilanlar");
                });

            modelBuilder.Entity("sellcar.entity.Marka", b =>
                {
                    b.Property<int>("MarkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adi")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("MarkaId");

                    b.ToTable("Markalar");
                });

            modelBuilder.Entity("sellcar.entity.Resim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.ToTable("Resimler");
                });

            modelBuilder.Entity("sellcar.entity.Fav", b =>
                {
                    b.HasOne("sellcar.entity.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sellcar.entity.Ilan", b =>
                {
                    b.HasOne("sellcar.entity.Il", "Il")
                        .WithMany("Ilanlar")
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sellcar.entity.Marka", "Marka")
                        .WithMany("Ilanlar")
                        .HasForeignKey("markaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sellcar.entity.Resim", b =>
                {
                    b.HasOne("sellcar.entity.Ilan", "Ilan")
                        .WithMany("IlanResimleri")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
